### ISSUE TITLE
chmod: cannot access 'extension/debugAdapters/mono.linux-x86_64': No such file or director

### ISSUE THREAD

**Issue by asher-gh** [Pocco81/DAPInstall.nvim#18]
Getting this error on installing `ccppr_vsc_dbg` on dev channel

**Comment by Pocco81** [comment]
Fixed! However, I don't think it should work. DAPInstall follows the instructions on [nvim-dap's wiki](https://github.com/mfussenegger/nvim-dap/wiki/C-C---Rust-(gdb-via--vscode-cpptools)) about the installation, but in one of the steps they require to make a file, which doesn't exist, executable.

I personally don't use this debugger, but you could open an issue in its repo :+1:
