### ISSUE TITLE
DIList fails on new install

### ISSUE THREAD

**Issue by kmclarnon** [Pocco81/DAPInstall.nvim#20]
Running `DIList` immediately after installing results in the following:

```
ls: cannot access '/home/kevin/.local/share/nvim/dapinstall/': No such file or directory

[Process exited 2]
```

I don't think this is unreasonable given that I haven't installed anything yet so the directory doesn't exist, but it seems like it might be a better user experience to handle that case [here](https://github.com/Pocco81/DAPInstall.nvim/blob/main/lua/dap-install/tools/tool_list/init.lua#L9) and return an empty list?

**Comment by Pocco81** [comment]
Thanks, I'm gonna add a more graceful handling for that :)
