### ISSUE TITLE
Where is the path in that list?

### ISSUE THREAD

**Issue by pedro757** [Pocco81/DAPInstall.nvim#22]
https://github.com/Pocco81/DAPInstall.nvim/blob/3083f7973ea477ed4132c089c27614bc88bf36b3/lua/dap-install/core/debuggers_list.lua#L3-L16

The README.md specifies this:

> Returns table of available debuggers in which the key is the name of the debugger and the value is another table in which index `1` has name of the module whithin DAPInstall.nvim and index `2` has the installation path.

but I don't think this works:

https://github.com/Pocco81/DAPInstall.nvim/blob/3083f7973ea477ed4132c089c27614bc88bf36b3/lua/dap-install/api/debuggers.lua#L9-L20

**Comment by Pocco81** [comment]
My bad. Did a refact and forgot to update that part of the doc and API. I'll fix this ASAP.
