### ISSUE TITLE
Error on launch: Attribute 'program' is not absolute ('{path}')

### ISSUE THREAD

**Issue by pedro757** [Pocco81/DAPInstall.nvim#34]
I'm new to dap, I don't know too much, but it seems that `jsnode` should have `${workspaceFolder}/${file}` in program

**This is the error:**

Error on launch: Attribute 'program' is not absolute ('{path}'); consider adding '${workspaceFolder}/' as a prefix to make it absolute.

**Comment by Pocco81** [comment]
Should be working now.

**Comment by pedro757** [comment]
I tried and it works!

**Comment by Pocco81** [comment]
Awesome! Now we can mark it as `tested` :)
