### ISSUE TITLE
unable to load modules on default configuration for python

### ISSUE THREAD

**Issue by Seidenschnabel2k** [Pocco81/DAPInstall.nvim#9]
not sure if this belongs here.
In the default environment,in the `python_dbg/pyvenv.cfg` the `include-system-site-packages = false` blocks every module I want to load. 

Sure I could install it in the venv. It still feels like a bug to me.

**Comment by Pocco81** [comment]
> not sure if this belongs here.

It does not actually. DAPInstall is for installing and managing debuggers and their configurations for nvim-dap, which means that settings particular to that debugger are not touched by DAPInstall.

I'd suggest you open this issue in [their repo](https://github.com/microsoft/debugpy) :+1:
